dist: xenial
sudo: required
services:
- docker
cache:
  directories:
    - $HOME/.cache/go-build
#    - $HOME/cached-deps
language: go
go:
- "1.11.1"
env:
  global:
    - PATH=$HOME/cached-deps:$PATH
  matrix:
    - BUCKET=MISC
    # If you want to update the number of PPS workers, you'll also need to update
    # the value in ./etc/build/PPS_BUILD_BUCKET_COUNT
    - BUCKET=PPS1
    - BUCKET=PPS2
    - BUCKET=PPS3
    - BUCKET=EXAMPLES
branches:
  except:
    - /^v[0-9]/
before_install:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.2.1/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
# Create a new Kubernetes cluster using KinD
- kind create cluster
# Set KUBECONFIG environment variable for KinD
- export KUBECONFIG="$(kind get kubeconfig-path)"
- pachctl port-forward &
#- sudo etc/testing/travis_before_install.sh
before_script:
- docker version
script:
- etc/testing/travis.sh
after_failure:
- kubectl version
- kubectl get all
- kubectl get all --namespace kafka
- kubectl describe pod -l app=pachd
- kubectl describe pod -l suite=pachyderm,app=etcd
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
