apiVersion: v1
kind: Secret
metadata:
  name: $PIPELINE_DOCKER_SECRETS
type: Opaque
data:
  # Any secret variables should go here
  # Refered environmental variables must end with _ENCODED
  # That is due to envsubst and magic required to make kubectl secrets
  # e.g. if you want to pass along $FOO_BAR, specify $FOO_BAR_ENCODED
  DATABASE_USERNAME: $DATABASE_USERNAME_ENCODED
  DATABASE_PASSWORD: $DATABASE_PASSWORD_ENCODED
  DATABASE_HOSTNAME: $DATABASE_HOSTNAME_ENCODED
  DATABASE_PORT: $DATABASE_PORT_ENCODED
