---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  labels:
    app: kafka
    suite: kafka
  name: kafka-storage-class
  namespace: default
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
