# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  go: circleci/go@1.6.0

parameters:
  run_flaky_tests:
    type: string
    default: ""
  retain_slots:
    type: string
    default: "0"

jobs:
  circleci:
    parameters:
      bucket:
        type: string
    resource_class: large
    machine:
      image: ubuntu-2004:202101-01
    environment:
      PPS_BUCKETS: "6"
      GOPROXY: https://proxy.golang.org
      BUCKET: << parameters.bucket >>
      BIGQUERY_PROJECT: alysha-dev-006
      BIGQUERY_DATASET: pach_test
      BIGQUERY_TABLE: test_runs
      TEST_RESULTS_BUCKET: pach-test-data
    steps:
      - checkout
      - restore_cache:
         keys:
         - pach-build-dependencies-v2-{{ checksum "etc/testing/circle/install.sh" }}
         - pach-build-dependencies-v2-
      - run: etc/testing/circle/install.sh 
      - save_cache:
         key: pach-build-dependencies-v2-{{ checksum "etc/testing/circle/install.sh" }}
         paths:
         - cached-deps/
      - run: etc/testing/circle/start-minikube.sh 
      - run: etc/testing/circle/launch-loki.sh
      - restore_cache:
         keys:
         - pach-go-build-cache-{{ .Branch }}
         - pach-go-build-cache
      - restore_cache:
         keys:
         - pach-go-mod-cache-{{ .Branch }}
         - pach-go-mod-cache
      - run: etc/testing/circle/build.sh 
      - run: etc/testing/circle/launch.sh 
      - run: etc/testing/circle/run_tests.sh 
      - save_cache:
         key: pach-go-mod-cache-{{ .Branch }}
         paths:
         - /home/circleci/.go_workspace/pkg/mod
      - save_cache:
         key: pach-go-build-cache-{{ .Branch }}
         paths:
         - /home/circleci/.gocache
      - run: etc/testing/circle/upload_stats.sh 
      - run:
          name: Dump debugging info in case of failure
          when: on_fail
          command: etc/testing/circle/kube_debug.sh
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results

workflows:
  circleci:
    jobs:
      - circleci:
          matrix:
            parameters:
              bucket:
              #- MISC
              # If you want to update the number of PPS buckets, you'll neet to
              # update the value of PPS_BUCKETS above
              #- AUTH
              - ENTERPRISE
              #- PFS
              #- PPS1
              #- PPS2
              #- PPS3
              #- PPS4
              # - PPS5
              #- PPS6
              #- EXAMPLES
              #- OBJECT
