deployTarget: LOCAL
dash:
  enabled: false
pachd:
  service:
    type: NodePort
  image:
    tag: local
  storage:
    local:
      requireRoot: false
      hostPath: /tmp/pachyderm/
  metrics:
    enabled: false
  resources:
    limits:
      cpu: 250m
      memory: 512M
    requests:
      cpu: 250m
      memory: 512M
postgresql:
  service:
    type: NodePort
